/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.EquipamentoDao;

/**
 *
 * @author John Peter
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    public static EquipamentoDao bdEquipamento;

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        bdEquipamento = new EquipamentoDao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btCliente = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btEquipamento = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btAluguel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuCadastro = new javax.swing.JMenu();
        JMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemEquipamento = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JMenuItemSair = new javax.swing.JMenuItem();
        jMenuAluguel = new javax.swing.JMenu();
        jMenuItemNovo = new javax.swing.JMenuItem();
        jMenuItemEmitir = new javax.swing.JMenuItem();
        jMenuItemEfetuar = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemEquipamentos = new javax.swing.JMenuItem();
        jMenuCAluguel = new javax.swing.JMenu();
        jMenuItemAbertos = new javax.swing.JMenuItem();
        jMenuItemRealizados = new javax.swing.JMenuItem();
        jMenuItemAviso = new javax.swing.JMenuItem();
        JMenuSuporte = new javax.swing.JMenu();
        JMenuItemAjuda = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        JMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipamentos de Informática");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/my-computer-icon.png"))); // NOI18N
        jLabel2.setText("J&L INFORMÁTICA");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/computer-stuff-1-e1465742115813.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jToolBar1.setBackground(new java.awt.Color(204, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/user-add-icon.png"))); // NOI18N
        btCliente.setText("Novo Cliente");
        btCliente.setFocusable(false);
        btCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btCliente);
        jToolBar1.add(jSeparator4);

        btEquipamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/my-computer-icon.png"))); // NOI18N
        btEquipamento.setText("Novo Equipamento");
        btEquipamento.setFocusable(false);
        btEquipamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEquipamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEquipamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(btEquipamento);
        jToolBar1.add(jSeparator3);

        btAluguel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/02-Basket-icon.png"))); // NOI18N
        btAluguel.setText("Novo Aluguel");
        btAluguel.setFocusable(false);
        btAluguel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAluguel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btAluguel);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        JMenuCadastro.setText("Cadastro");
        JMenuCadastro.setName("JMenuCadastro"); // NOI18N

        JMenuItemCliente.setText("Cliente");
        JMenuItemCliente.setName("JMenuItemCliente"); // NOI18N
        JMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemClienteActionPerformed(evt);
            }
        });
        JMenuCadastro.add(JMenuItemCliente);

        jMenuItemEquipamento.setText("Equipamento");
        jMenuItemEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEquipamentoActionPerformed(evt);
            }
        });
        JMenuCadastro.add(jMenuItemEquipamento);
        JMenuCadastro.add(jSeparator1);

        JMenuItemSair.setText("Sair");
        JMenuItemSair.setName("JMenuItemSair"); // NOI18N
        JMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemSairActionPerformed(evt);
            }
        });
        JMenuCadastro.add(JMenuItemSair);

        jMenuBar1.add(JMenuCadastro);

        jMenuAluguel.setText("Aluguel");

        jMenuItemNovo.setText("Novo Aluguel");
        jMenuAluguel.add(jMenuItemNovo);

        jMenuItemEmitir.setText("Emitir Contrato");
        jMenuAluguel.add(jMenuItemEmitir);

        jMenuItemEfetuar.setText("Efetuar Devolução");
        jMenuAluguel.add(jMenuItemEfetuar);

        jMenuBar1.add(jMenuAluguel);

        jMenuConsulta.setText("Consulta");

        jMenuItemCliente.setText("Cliente");
        jMenuConsulta.add(jMenuItemCliente);

        jMenuItemEquipamentos.setText("Equipamentos");
        jMenuConsulta.add(jMenuItemEquipamentos);

        jMenuCAluguel.setText("Aluguel");

        jMenuItemAbertos.setText("Aluguel Aberto");
        jMenuCAluguel.add(jMenuItemAbertos);

        jMenuItemRealizados.setText("Aluguel Realizado");
        jMenuCAluguel.add(jMenuItemRealizados);

        jMenuItemAviso.setText("Aviso de Vencimento");
        jMenuCAluguel.add(jMenuItemAviso);

        jMenuConsulta.add(jMenuCAluguel);

        jMenuBar1.add(jMenuConsulta);

        JMenuSuporte.setText("Suporte");
        JMenuSuporte.setName("JMenuSuporte"); // NOI18N

        JMenuItemAjuda.setText("Ajuda");
        JMenuItemAjuda.setName("JMenuItemAjuda"); // NOI18N
        JMenuSuporte.add(JMenuItemAjuda);
        JMenuSuporte.add(jSeparator2);

        JMenuItemSobre.setText("Sobre");
        JMenuItemSobre.setName("JMenuItemSobre"); // NOI18N
        JMenuSuporte.add(JMenuItemSobre);

        jMenuBar1.add(JMenuSuporte);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(772, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void JMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMenuItemSairActionPerformed

    private void JMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemClienteActionPerformed
        new FormCliente().setVisible(true);
    }//GEN-LAST:event_JMenuItemClienteActionPerformed

    private void jMenuItemEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEquipamentoActionPerformed
        new FormEquipamento().setVisible(true);
    }//GEN-LAST:event_jMenuItemEquipamentoActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        JMenuItemClienteActionPerformed(evt);
    }//GEN-LAST:event_btClienteActionPerformed

    private void btEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEquipamentoActionPerformed
        jMenuItemEquipamentoActionPerformed(evt);
    }//GEN-LAST:event_btEquipamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuCadastro;
    private javax.swing.JMenuItem JMenuItemAjuda;
    private javax.swing.JMenuItem JMenuItemCliente;
    private javax.swing.JMenuItem JMenuItemSair;
    private javax.swing.JMenuItem JMenuItemSobre;
    private javax.swing.JMenu JMenuSuporte;
    private javax.swing.JButton btAluguel;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btEquipamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuAluguel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCAluguel;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenuItem jMenuItemAbertos;
    private javax.swing.JMenuItem jMenuItemAviso;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemEfetuar;
    private javax.swing.JMenuItem jMenuItemEmitir;
    private javax.swing.JMenuItem jMenuItemEquipamento;
    private javax.swing.JMenuItem jMenuItemEquipamentos;
    private javax.swing.JMenuItem jMenuItemNovo;
    private javax.swing.JMenuItem jMenuItemRealizados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
